# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stixel/protos/stixel_world.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'stixel/protos/stixel_world.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n stixel/protos/stixel_world.proto\x12\x0bstixelworld\"\x82\x01\n\x06Stixel\x12\t\n\x01u\x18\x01 \x01(\x05\x12\x0b\n\x03v_t\x18\x02 \x01(\x05\x12\x0b\n\x03v_b\x18\x03 \x01(\x05\x12\t\n\x01\x64\x18\x04 \x01(\x02\x12%\n\x05label\x18\x05 \x01(\x0e\x32\x16.stixelworld.LabelType\x12\r\n\x05width\x18\x06 \x01(\x05\x12\x12\n\nconfidence\x18\x07 \x01(\x02\"\xaf\x01\n\nCameraInfo\x12\t\n\x01K\x18\x01 \x03(\x02\x12\t\n\x01T\x18\x02 \x03(\x02\x12\t\n\x01R\x18\x03 \x03(\x02\x12\t\n\x01\x44\x18\x04 \x03(\x02\x12\x12\n\ndist_model\x18\x05 \x01(\t\x12\x10\n\x08img_name\x18\x06 \x01(\t\x12\x11\n\treference\x18\x07 \x01(\t\x12\x12\n\x05width\x18\x08 \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x06height\x18\t \x01(\x05H\x01\x88\x01\x01\x42\x08\n\x06_widthB\t\n\x07_height\"%\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\"\x88\x01\n\x0bStixelWorld\x12(\n\x0bstixel_list\x18\x01 \x03(\x0b\x32\x13.stixelworld.Stixel\x12,\n\x0b\x63\x61mera_info\x18\x02 \x01(\x0b\x32\x17.stixelworld.CameraInfo\x12!\n\x05image\x18\x03 \x01(\x0b\x32\x12.stixelworld.Image*\xca\x03\n\tLabelType\x12\x12\n\x0eTYPE_UNDEFINED\x10\x00\x12\x0c\n\x08TYPE_CAR\x10\x01\x12\x0e\n\nTYPE_TRUCK\x10\x02\x12\x0c\n\x08TYPE_BUS\x10\x03\x12\x16\n\x12TYPE_OTHER_VEHICLE\x10\x04\x12\x15\n\x11TYPE_MOTORCYCLIST\x10\x05\x12\x12\n\x0eTYPE_BICYCLIST\x10\x06\x12\x13\n\x0fTYPE_PEDESTRIAN\x10\x07\x12\r\n\tTYPE_SIGN\x10\x08\x12\x16\n\x12TYPE_TRAFFIC_LIGHT\x10\t\x12\r\n\tTYPE_POLE\x10\n\x12\x1a\n\x16TYPE_CONSTRUCTION_CONE\x10\x0b\x12\x10\n\x0cTYPE_BICYCLE\x10\x0c\x12\x13\n\x0fTYPE_MOTORCYCLE\x10\r\x12\x11\n\rTYPE_BUILDING\x10\x0e\x12\x13\n\x0fTYPE_VEGETATION\x10\x0f\x12\x13\n\x0fTYPE_TREE_TRUNK\x10\x10\x12\r\n\tTYPE_CURB\x10\x11\x12\r\n\tTYPE_ROAD\x10\x12\x12\x14\n\x10TYPE_LANE_MARKER\x10\x13\x12\x15\n\x11TYPE_OTHER_GROUND\x10\x14\x12\x11\n\rTYPE_WALKABLE\x10\x15\x12\x11\n\rTYPE_SIDEWALK\x10\x16\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stixel.protos.stixel_world_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LABELTYPE']._serialized_start=539
  _globals['_LABELTYPE']._serialized_end=997
  _globals['_STIXEL']._serialized_start=50
  _globals['_STIXEL']._serialized_end=180
  _globals['_CAMERAINFO']._serialized_start=183
  _globals['_CAMERAINFO']._serialized_end=358
  _globals['_IMAGE']._serialized_start=360
  _globals['_IMAGE']._serialized_end=397
  _globals['_STIXELWORLD']._serialized_start=400
  _globals['_STIXELWORLD']._serialized_end=536
# @@protoc_insertion_point(module_scope)
